const data = [
  {
    id: 1,
    title: "ARIES",
    date: "21 March - 20 April",
    quartet: "pioneer",
    element: "fire",
    birthstones: "aquamarine, jasper , diamond",
    desc: "The first sign of astrology is Aries. People with Aries are active, energetic, free and courageous people. They like to manipulate people. People under the sign of Aries are enthusiastic and goal-oriented. In addition to having leadership qualities, they are courageous and assertive, and due to these characteristics, they can easily guide other people.",
    image: "./img/horoscope-aries.jpg",
  },
  {
    id: 2,
    title: "TAURUS",
    date: "20 April - 20 May",
    quartet: "fixed",
    element: "earth",
    birthstones: "emerald, agate, turquoise",
    desc: "Taurus is a reliable and stubborn zodiac sign. They are people who have a large group of friends with their warm personalities. They are generally described as art lovers. It has been observed that they often act with their emotions. Although Taurus people are self-indulgent and like to be lazy, with the contribution of their stubborn personalities, they can be determined about the things they want most and thus achieve success.",
    image: "./img/horoscope-taurus.jpg",
  },
  {
    id: 3,
    title: "GEMINI",
    date: "21 May - 21 June",
    quartet: "mutable",
    element: "air",
    birthstones: "alexandrite, jade, tiger eye",
    desc: "Gemini people are known for experiencing multiple emotions at the same time. People belonging to the Gemini zodiac sign may not keep one memory of the other, so they are expressed as unbalanced by many people. Gemini people like to socialize and talk, so they are very popular in their environment. Gemini people have high self-confidence and are defined as an attractive personality in social environments.",
    image: "./img/horoscope-gemini.jpg",
  },
  {
    id: 4,
    title: "CANCER",
    date: "22 June - 21 July",
    quartet: "pioneer",
    element: "water",
    birthstones: "ruby, amethyst, chalcedony",
    desc: "People belonging to the Cancer sign are known as sensitive and emotional people by their environment. Because of their sensitivity, Cancer people can be easily offended and hurt very quickly. As they fill their families, they become thinkers. They are sensitive and caring not only to their families but to every person they meet, so the emotional bonds they form with the people around them are very strong. They are known as responsible people in their social and business lives.",
    image: "./img/horoscope-cancer.jpg",
  },
  {
    id: 5,
    title: "LEO",
    date: "22 July - 23 August",
    quartet: "fixed",
    element: "fire",
    birthstones: "agate, amethyst, amber",
    desc: "People of the Leo sign are authoritarian and like to manage the people around them in both social and business life. Leos are also generous and self-sacrificing people. When the people around them are in trouble, they do everything they can to help them, so they are loved and respected around them.",
    image: "./img/horoscope-leo.jpg",
  },
  {
    id: 6,
    title: "VİRGO",
    date: "23 August - 23 September",
    quartet: "mutable",
    element: "earth",
    birthstones: "emerald, sapphire, topaz",
    desc: "Virgo people are very organized and meticulous in their work. They do not make sudden decisions, whatever they are doing, they first analyze and decide by thinking. They care about cleanliness and order. This is one of their strongest traits as they approach everything logically, and they can find practical and rational solutions to problems.",
    image: "./img/horoscope-virgo.jpg",
  },
  {
    id: 7,
    title: "LİBRA",
    date: "23 September - 23 October",
    quartet: "pioneer",
    element: "air",
    birthstones: "jade, pearl, topaz",
    desc: "Libra, people of the zodiac sign are recognized diplomatically in their environment and come to the fore with these features. Because Libras are diplomatic, they can establish good relations with almost everyone, including people with opposing views. He is ambitious in business life, has high ambitions for success and making money. They do not hesitate to spend their earnings on expensive pleasures and goods. They exhibit a very attractive appearance in their environment.",
    image: "./img/horoscope-libra.jpg",
  },
  {
    id: 8,
    title: "SCORPİO",
    date: "23 October - 22 November",
    quartet: "fixed",
    element: "water",
    birthstones: "aquamarine, sapphire, black pearl",
    desc: "Scorpio people are known for their passionate lifestyles. In social life, with their friendly personalities and attractive images, they easily enter any environment and make themselves loved. They prioritize the mind and love to question. For Scorpio people, revenge is like a dish best served cold. If a wrong has been done against them, they never forget it and when the time comes, they take action to take revenge.",
    image: "./img/horoscope-scorpio.jpg",
  },
  {
    id: 9,
    title: "SAGITTARIUS",
    date: "22 november - 23 December",
    quartet: "mutable",
    element: "fire",
    birthstones: "amethyst, sapphire, turquoise",
    desc: "Sagittarius people have a positive and lively personality towards life. In social life, a Sagittarius is easy to meet new people and they like to have fun with their friends. They have positive thinking and good intentions, but this may cause them to make wrong decisions from time to time and to regret these decisions. ",
    image: "./img/horoscope-sagittarius.jpg",
  },
  {
    id: 10,
    title: "CAPRİCORN",
    date: "22 October - 23 December",
    quartet: "mutable",
    element: "fire",
    birthstones: "amethyst, sapphire, turquoise",
    desc: "Sagittarius people have a positive and lively personality towards life. In social life, a Sagittarius is easy to meet new people and they like to have fun with their friends. They have positive thinking and good intentions, but this may cause them to make wrong decisions from time to time and to regret these decisions. ",
    image: "./img/horoscope-sagittarius.jpg",
  },
  {
    id: 11,
    title: "Arashiyama Bamboo Grove",
    desc: "Bamboo Forest, or Arashiyama Bamboo Grove or Sagano Bamboo Forest, is a natural forest of bamboo in Arashiyama, Kyoto, Japan. The forest consists mostly of Moso Bamboo (Phyllostachys edulis) and consists of several pathways for tourists and visitors. The Ministry of the Environment considers it a part of the soundscape of Japan.",
    image: "https://wallpaperaccess.com/full/534182.jpg",
  },
  {
    id: 12,
    title: "Antelope Canyon",
    desc: "Antelope Canyon is a slot canyon in the American Southwest, on Navajo land east of Page, Arizona. It includes two separate, scenic slot canyon sections, referred to as Upper Antelope Canyon (or The Crack), and Lower Antelope Canyon (or The Corkscrew).",
    image:
      "https://images.unsplash.com/photo-1444076784383-69ff7bae1b0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTJ8fGxvd2VyJTIwYW50ZWxvcGUlMjBjYW55b258ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
  },
];
export default data;
